module.exports.listMitra = [
  {
    id_field_name: 'entity_id',
    entity_id: '65',
    is_seller: '1',
    seller_id: '293',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'bvnusantaracom',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-03-25 22:36:21',
    updated_at: '2025-03-25 15:36:21',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/293/seller_panel/1/' target='blank' title='View Customer'>Banten Vacation</a>",
    email: 'imam.mamduhjamaludin@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/293/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/293/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '293',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '62',
    is_seller: '1',
    seller_id: '283',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'wonderfulselaya',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-03-19 13:50:12',
    updated_at: '2025-03-19 06:50:12',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/283/seller_panel/1/' target='blank' title='View Customer'>Wonderful Syahrir</a>",
    email: 'wonderfulselayar@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/283/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/283/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '283',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '60',
    is_seller: '1',
    seller_id: '282',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'koperandulu',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-03-18 15:14:37',
    updated_at: '2025-03-18 08:14:37',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/282/seller_panel/1/' target='blank' title='View Customer'>Fei Fei</a>",
    email: 'fei.wiharjo@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/282/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/282/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '282',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '59',
    is_seller: '1',
    seller_id: '281',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'jadiberangkat',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-03-18 01:08:25',
    updated_at: '2025-03-17 18:08:25',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/281/seller_panel/1/' target='blank' title='View Customer'>JadiBerangkat Tour Organizer</a>",
    email: 'jadiberangkattour@gmail.com',
    billing_telephone: '085186854343',
    billing_postcode: '68467',
    billing_country_id: 'ID',
    billing_region: 'JAWA TIMUR',
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/281/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/281/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '281',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '58',
    is_seller: '1',
    seller_id: '276',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'rentcarmalang',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-03-14 13:43:05',
    updated_at: '2025-03-14 06:43:05',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/276/seller_panel/1/' target='blank' title='View Customer'>Pungky Rachmanto</a>",
    email: 'pungkyrachmanto46@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/276/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/276/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '276',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '54',
    is_seller: '1',
    seller_id: '273',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'Tibersaholidays',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-03-12 13:04:33',
    updated_at: '2025-03-12 06:04:33',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/273/seller_panel/1/' target='blank' title='View Customer'>Fadhil Raihan</a>",
    email: 'Fraihan.business@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/273/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/273/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '273',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '52',
    is_seller: '1',
    seller_id: '263',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'hojo-treepark',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-03-06 15:07:53',
    updated_at: '2025-03-06 08:07:53',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/263/seller_panel/1/' target='blank' title='View Customer'>Hojo TreePark Tangerang</a>",
    email: 'reservation.hjwtangerang@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/263/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/263/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '263',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '48',
    is_seller: '1',
    seller_id: '248',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'gemini-tour',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-02-13 15:35:06',
    updated_at: '2025-02-13 08:35:06',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/248/seller_panel/1/' target='blank' title='View Customer'>GEMINI TRAVEL</a>",
    email: 'hfd.nagatamakarya@gmail.com',
    billing_telephone: '08567034799',
    billing_postcode: '12790',
    billing_country_id: 'ID',
    billing_region: 'Daerah Khusus Ibukota',
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/248/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/248/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '248',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '46',
    is_seller: '1',
    seller_id: '238',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'httpswwwlmsrent',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2025-01-20 20:10:21',
    updated_at: '2025-01-20 13:10:21',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/238/seller_panel/1/' target='blank' title='View Customer'>LMS RENT</a>",
    email: 'lenteramultisupply@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/238/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/238/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '238',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '44',
    is_seller: '1',
    seller_id: '163',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'curaweda',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-12-05 16:19:28',
    updated_at: '2025-02-12 06:11:48',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/163/seller_panel/1/' target='blank' title='View Customer'>Liburdulu Official</a>",
    email: 'official@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/163/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/163/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '163',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '37',
    is_seller: '1',
    seller_id: '108',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'platdvacation',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-09-18 06:03:30',
    updated_at: '2024-11-28 07:04:50',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/108/seller_panel/1/' target='blank' title='View Customer'>PlatD Vacation</a>",
    email: 'platd.vacation@gmail.com',
    billing_telephone: '087822844699',
    billing_postcode: '40287',
    billing_country_id: 'ID',
    billing_region: 'Jawa Barat',
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/108/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/108/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '108',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '34',
    is_seller: '1',
    seller_id: '105',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'titiknoltravel',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-09-06 10:57:43',
    updated_at: '2024-09-06 03:57:43',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/105/seller_panel/1/' target='blank' title='View Customer'>titiknol travel</a>",
    email: 'titiknol.travel@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/105/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/105/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '105',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '31',
    is_seller: '1',
    seller_id: '66',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'travelbuddies',
    shop_title: 'Travel Buddies',
    logo_pic: null,
    company_locality: 'Jakarta',
    country_pic: 'ID',
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-22 14:12:56',
    updated_at: '2024-11-28 07:04:50',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: '0',
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/66/seller_panel/1/' target='blank' title='View Customer'>Travel Buddies</a>",
    email: 'travelbuddies@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/66/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/66/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '66',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '29',
    is_seller: '1',
    seller_id: '33',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'ubuvilla',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-09 14:13:17',
    updated_at: '2024-08-09 07:13:17',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/33/seller_panel/1/' target='blank' title='View Customer'>ubu villa</a>",
    email: 'ubuvilla@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/33/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/33/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '33',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '27',
    is_seller: '1',
    seller_id: '32',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'jeepmerapi',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-09 10:18:02',
    updated_at: '2024-08-09 03:18:02',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/32/seller_panel/1/' target='blank' title='View Customer'>jeep merapi</a>",
    email: 'jeepmerapi@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/32/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/32/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '32',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '24',
    is_seller: '1',
    seller_id: '31',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'victoryrentcar',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-08 20:35:02',
    updated_at: '2024-11-28 07:04:50',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/31/seller_panel/1/' target='blank' title='View Customer'>VICTORY RENT CAR AND TOUR</a>",
    email: 'victoryrent@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/31/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/31/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '31',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '22',
    is_seller: '1',
    seller_id: '30',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'miraclehotel',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-08 20:21:42',
    updated_at: '2024-11-28 07:04:50',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/30/seller_panel/1/' target='blank' title='View Customer'>Miracle Hotel Management</a>",
    email: 'miraclehotelmanagement@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/30/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/30/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '30',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '20',
    is_seller: '1',
    seller_id: '29',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'campervan',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-08 18:38:47',
    updated_at: '2024-08-08 11:38:47',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/29/seller_panel/1/' target='blank' title='View Customer'>campervan campervan</a>",
    email: 'campervan@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/29/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/29/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '29',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '18',
    is_seller: '1',
    seller_id: '28',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'funtrip',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-08 18:36:58',
    updated_at: '2024-08-08 11:36:58',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/28/seller_panel/1/' target='blank' title='View Customer'>Fun Trip</a>",
    email: 'funtrip@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/28/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/28/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '28',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '15',
    is_seller: '1',
    seller_id: '27',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'navistour',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-06 13:14:30',
    updated_at: '2024-08-06 06:14:30',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/27/seller_panel/1/' target='blank' title='View Customer'>Navis Tour Travel</a>",
    email: 'navistour@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/27/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/27/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '27',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '13',
    is_seller: '1',
    seller_id: '26',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'soapspa',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-05 15:56:05',
    updated_at: '2024-08-05 08:56:05',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/26/seller_panel/1/' target='blank' title='View Customer'>Soap and Sea</a>",
    email: 'soapspa@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/26/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/26/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '26',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '11',
    is_seller: '1',
    seller_id: '22',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'haitraveller',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-08-01 14:27:42',
    updated_at: '2024-11-28 07:04:50',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/22/seller_panel/1/' target='blank' title='View Customer'>HaiTraveller HaiTraveller</a>",
    email: 'haitraveller@liburdulu.id',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/22/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/22/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '22',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '9',
    is_seller: '1',
    seller_id: '19',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'mhm',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-07-29 16:22:34',
    updated_at: '2024-11-28 07:04:50',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/19/seller_panel/1/' target='blank' title='View Customer'>My Hospitality Management</a>",
    email: 'mhm@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/19/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/19/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '19',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '7',
    is_seller: '1',
    seller_id: '18',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'penidago',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-07-29 12:45:44',
    updated_at: '2024-07-29 05:45:44',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/18/seller_panel/1/' target='blank' title='View Customer'>Penidago Tour</a>",
    email: 'penidago@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/18/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/18/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '18',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '5',
    is_seller: '1',
    seller_id: '17',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '0',
    vimeo_active: '0',
    instagram_active: '0',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '0',
    others_info: null,
    banner_pic: null,
    shop_url: 'opitravel',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-07-26 11:57:35',
    updated_at: '2024-11-28 07:04:50',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/17/seller_panel/1/' target='blank' title='View Customer'>Opi Travel</a>",
    email: 'opi@gmail.com',
    billing_telephone: null,
    billing_postcode: null,
    billing_country_id: null,
    billing_region: null,
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/17/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/17/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '17',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
  {
    id_field_name: 'entity_id',
    entity_id: '2',
    is_seller: '1',
    seller_id: '8',
    payment_source: null,
    twitter_id: null,
    facebook_id: null,
    gplus_id: null,
    youtube_id: null,
    vimeo_id: null,
    instagram_id: null,
    pinterest_id: null,
    moleskine_id: null,
    tiktok_id: null,
    tw_active: '0',
    fb_active: '0',
    gplus_active: '0',
    youtube_active: '1',
    vimeo_active: '0',
    instagram_active: '1',
    pinterest_active: '0',
    moleskine_active: '0',
    tiktok_active: '1',
    others_info: null,
    banner_pic: null,
    shop_url: 'jalanduluaja',
    shop_title: null,
    logo_pic: null,
    company_locality: null,
    country_pic: null,
    company_description: null,
    meta_keyword: null,
    meta_description: null,
    background_width: null,
    store_id: '0',
    contact_number: null,
    return_policy: null,
    shipping_policy: null,
    created_at: '2024-07-18 15:56:04',
    updated_at: '2024-11-26 11:23:36',
    admin_notification: '0',
    privacy_policy: null,
    allowed_categories: '',
    allowed_attributeset_ids: '',
    is_separate_panel: null,
    low_stock_quantity: null,
    fulfilment_image: null,
    fulfilment_text: null,
    name: "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/8/seller_panel/1/' target='blank' title='View Customer'>admin jda</a>",
    email: 'jda@liburdulu.id',
    billing_telephone: '585-598-8140',
    billing_postcode: '14623',
    billing_country_id: 'ID',
    billing_region: 'New York',
    website_id: '1',
    flagcount:
      "<a href='https://backend2.liburdulu.id/admin/customer/index/edit/id/8/seller_panel/1/' target='blank' title='View Flags'>0</a>",
    orig_data: null,
    actions: {
      view: {
        href: 'https://backend2.liburdulu.id/admin/marketplace/order/index/seller_id/8/',
        label: 'Order',
      },
    },
    pro_deny_html: "<button class='button'><span>Deny</span></button>",
    pro_deny_title: 'What is the reason to deny this seller?',
    pro_deny_submitlabel: 'Deny',
    pro_deny_cancellabel: 'Reset',
    pro_deny_sellerid: '8',
    pro_deny_formaction:
      'https://backend2.liburdulu.id/admin/marketplace/seller/deny/',
  },
];
